language: java
sudo: true # must have same "sudo" state in stages for caching

# avoid double builds on pull requests
branches:
  only:
    master

# caches for build artifacts
cache:
  directories:
    - $HOME/travis_cache

jobs:
  include:
    # build cache
    - stage: Build cache
      install: true
      script:
        - mv $HOME/travis_cache $HOME/travis_cache_old
        - mkdir $HOME/travis_cache
        - echo "$TRAVIS_BUILD_ID" > $HOME/travis_cache/travis_build_id

    # Check format
    - stage: Check format
      # do not use default install (runs formatter)
      install: true
      script: mvn -Pcheck-formatted validate formatter:validate

    # build + test
    - stage: Build + test
      os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages: oracle-java8-installer
      # before_cache: cp phoenicis-dist/target/*.deb $HOME/travis_cache/
    - stage: Build + test
      os: linux
      dist: trusty
      jdk: oraclejdk9
      addons:
        apt:
          packages: oracle-java9-installer
    - stage: Build + test
      os: osx
      osx_image: xcode9.2

    # Install packages
    # debug
    - stage: Install packages
      install: true
      script: ls $HOME/travis_cache/
    # .deb
    - stage: Install packages
      install: true
      script:
        - ls $HOME/travis_cache/
        # check that cache has been filled in current build
        - if test "$TRAVIS_BUILD_ID" != `cat $HOME/travis_cache/travis_build_id`; then travis_terminate 1; fi
        - rm -f $HOME/travis_cache/travis_build_id
        - sudo dpkg -i $HOME/travis_cache/*.deb && sudo apt install -fy
        - mv $HOME/travis_cache $HOME/travis_cache_old
        - mkdir $HOME/travis_cache # clear the cache

    # Check GitHub Pages
    - stage: Check GitHub Pages
      env: NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      language: ruby
      rvm:
        - 2.5
      before_install: cd docs
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
